[package]
name = "pingling-primitive-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
pingling-core-mock.workspace = true
pingling-core-process.workspace = true
pingling-core-singbox.workspace = true
pingling-domain.workspace = true
pingling-host-contract.workspace = true
serde_json.workspace = true
